package org.mp.chiproject2.tools

object DescriptionList {

    val descriptionList = arrayListOf(
        "From the outside this house looks snug and comfortable. It has been built with walnut wood and has spruce wooden decorations. Small, octagon windows allow enough light to enter the home and have been added to the house in a very asymmetric way. The house is equipped with a huge kitchen and one small bathroom, it also has a warm living room, three bedrooms, a grand dining area and a snug basement.",
        "From the outside this house looks stylish. It has been built with white pine wood and has mahogany wooden decorations. Tall, rounded windows add to the overall look of the house and have been added to the house in a fairly asymmetrical pattern. The house is equipped with a modern kitchen and one small bathroom, it also has a huge living room, four bedrooms, a spacious dining room, a multimedia room and a modest garage.",
        "From the outside this house looks lavish. It has been built with sandstone and has cypress wooden decorations. Short, wide windows allow enough light to enter the home and have been added to the house in a very symmetric way. The house is equipped with a small kitchen and one average bathroom, it also has a warm living room, three bedrooms, a cozy dining room, a game room and a cozy garage.",
        "The building is shaped like a circle. The house is half surrounded by stylish gardens. The second floor is smaller than the first, which allowed for a roof garden on two sides of the house. This floor has roughly the same style as the floor below. The roof is high and slanted to one side and is covered with overlapping roof tiles. There are no chimneys.",
        "From the outside this house looks lavish. It has been built with spruce wood and has sandstone decorations. Small, octagon windows let in plenty of light and have been added to the house in a very asymmetric way. The house is equipped with an average kitchen and one large bathroom, it also has a generous living room, five bedrooms, a cozy dining area, a playroom and a snug basement.",
        "From the outside this house looks impressive. It has been built with grey bricks and has granite decorations. Tall, rounded windows brighten up the house and have been added to the house in a mostly asymmetric way. The house is equipped with a small kitchen and three bathrooms, it also has a large living room, two bedrooms, a spacious dining area, a playroom and a modest basement.",
        "The building is shaped like a T. The two extensions are linked by a patio circling around half the house. The second floor is bigger than the first, which creates several overhanging parts on several sides of the house. This floor has a slightly different style than the floor below.",
        "The roof is low, triangular and layered and is covered with stone slabs. One large chimney sits at the side of the house. Two roof terraces let in plenty of light to the rooms below the roof. The house itself is surrounded by paved ground, with an outdoor eating and relaxing space and various potted plants.",
        "From the outside this house looks warm and cozy. It has been built with spruce wood and has blue stone decorations. Tall, rounded windows brighten up the house and have been added to the house in a very symmetric way. The house is equipped with an average kitchen and two bathrooms, it also has a spacious living room, three bedrooms, a spacious dining room and a small garage.",
        "The building is square shaped. The house is fully surrounded by stylish gardens. The second floor is bigger than the first, which creates a stylish overhang on two sides of the house. This floor has a slightly different style than the floor below.",
        "The roof is low and rounded and is covered with grey ceramic tiles. There are no chimneys. Rows of small windows let in plenty of light to the rooms below the roof. The house itself is surrounded by paved ground, with various party spots, like a fancy barbeque and a firepit.",
        "From the outside this house looks snug and comfortable. It has been built with brown bricks and has burgandy brick decorations. Tall, rounded windows allow enough light to enter the home and have been added to the house in a mostly symmetric way. The house is equipped with an old-fashioned kitchen and two bathrooms, it also has a huge living room, four bedrooms, a spacious dining area and a spacious garage."
    )

}